---
title : '<h2>Descriptive Statistics'
author: '95-845 AAMLP <hr><b>Final Project</b> <br><br><h4>Nathan Deron <br>David Contreras <br>Laura Goyeneche'
date  : '<h5>10/30/2019'
output:
  html_document:
     theme: cerulean
     toc: true
     code_folding: hide
     highlight: tango
---

```{r setup, include = F}
knitr::opts_chunk$set(echo = T, cache = T)
```

```{r, include = F}
# Define libraries
libs = c('httr','jsonlite',
         'dplyr',
         'stringr',
         'readr','data.table',
         'lubridate',
         'knitr','kableExtra',
         'fastDummies',
         'papeR',
         'ggcorrplot','plotly','GGally',
         'leaflet')

# Attach libraries
invisible(suppressMessages(lapply(libs, library, character.only = T)))
```

```{r}
# Working directory
cd = 'C:/Users/lgoye/OneDrive/Documents/Github/aamlp_chicago_rides'
setwd(cd)

# Import data
# City of Chicago

  # Import 3 datasets
  # Taxi trips 1.3 out of 187 million observations 
  # Other providers trips: 8.9 out of 101 million observations
  # Crime in Chicago: 35,494 out of 7 million observations

  df_taxi  = readRDS(paste0(cd, '/data_rds/df_taxi.rds'))
  df_other = readRDS(paste0(cd, '/data_rds/df_other.rds'))
  df_crime = readRDS(paste0(cd, '/data_rds/df_crime.rds'))
```

```{r}
# Data pre-processing 
# Taxi trips

names(df_taxi) = tolower(names(df_taxi))
names(df_taxi) = gsub(".", "_", names(df_taxi), fixed = T)

taxi = 
  df_taxi %>%
  
    # Create time variables: year, month, hour
    mutate(date_start = mdy_hms(trip_start_timestamp %>% as.character()),
           date_end   = mdy_hms(trip_end_timestamp %>% as.character()),
           year       = year(date_start),
           month      = month(date_start)) %>%

    # Remove timestamp variables and pickup location
    select(-trip_start_timestamp,
           -trip_end_timestamp,
           -pickup_centroid_location,
           -dropoff_centroid__location) %>%

    # Generate factor variables
    mutate(payment_type = as.factor(payment_type),
          company      = as.factor(company),
          trip_id      = as.factor(trip_id),
          taxi_id      = as.factor(taxi_id)) %>%
  
    # Destring numeric variables
    mutate_if(is.character, as.numeric)

# Ridesharing trips
names(df_other) = tolower(names(df_other))
other = 
  df_other %>%
  mutate_if(is.character, as.numeric)

# Crime 
names(df_crime) = tolower(names(df_crime))
crime = 
  df_crime %>%
  mutate_if(is.character, as.numeric)
  
```

## Taxi trips
### General summary 
```{r, warning = F, message = F}
taxi %>%
  select(-pickup_census_tract, 
         -pickup_community_area,
         -pickup_centroid_latitude,
         -pickup_centroid_longitude,
         -dropoff_census_tract,
         -dropoff_community_area,
         -dropoff_centroid_latitude,
         -dropoff_centroid_longitude) %>%
  select_if(is.numeric) %>% 
  as.data.frame() %>%
  papeR::summarize(show.NAs = T) %>%
  kable() %>%
  kable_styling(full_width = F)
```

```{r}
# From the general summary we can observe that they are trip that last almost a day and that the trip miles is 25 times the maximum number of miles from south-north and west-east in Chicago. Given that we filter by:
  # Maximum number of miles: 35 miles
  # Maximum trip duration: 1h

taxi =
  taxi %>%
  filter(trip_miles < 35,
         trip_seconds < 3600)
```

### Summary of NAs
```{r, warning = F, message = F}
taxi %>%
  is.na() %>%
  colSums() %>%
  data.frame(countNA = .) %>%
  add_rownames(var = "Variable") %>%
  filter(countNA > 0) %>%
  kable(col.names = c("","Number of NAs")) %>%
  kable_styling(full_width = F)
```

```{r}
# NA Taxi id and prices (fare, tips, tolls, extras and total) correlated? No! 
table(is.na(taxi$taxi_id), is.na(taxi$tips)) %>%
  kable() %>%
  kable_styling(full_width = F)
```

### Distribution of trips across hours
```{r, warning = F, message = F}
taxi %>%
  # Pickup hour
  mutate(hour_start = format(date_start, "%H:%M")) %>%
  
  # Count number of trip by hour
  group_by(hour_start) %>%
  summarise(freq = n()) %>%
  rename(hour = hour_start) %>%
  mutate(category = "Pickup hour") %>%

  bind_rows(
    taxi %>%
    
      # Dropoff hour
      mutate(hour_end = format(date_end, "%H:%M")) %>%
      group_by(hour_end) %>%
      summarise(freq = n()) %>%
      rename(hour = hour_end) %>%
      mutate(category = "Dropoff hour")
  ) %>%
    
  # Scatter plot
  plot_ly(x      =~ hour, 
          y      =~ freq, 
          color  =~ category, 
          colors = c("#FAA916","#02040F"),
          type   = "scatter", 
          mode   = "marker") %>%
  layout(xaxis   = list(title = "Hour"),
         yaxis   = list(title = "Number of taxi trips"))
  
```

### Top 10 pickup and dropoff CA
```{r, warning = F, message = F}
taxi %>%
  # Count number of trips by pickup community area
  filter(!is.na(pickup_community_area)) %>%
  group_by(pickup_community_area) %>%
  summarise(freq = n()) %>%
  
  # Select top 10
  arrange(-freq) %>%
  head(n = 10) %>%
  
  rename(com_area = pickup_community_area) %>%
  mutate(category = "Pickup") %>%
  
  # Append number of trips by dropoff community area
  bind_rows(
    
    taxi %>% 
    filter(!is.na(dropoff_community_area)) %>%
    group_by(dropoff_community_area) %>%
    summarise(freq = n()) %>%
    
    # Select top 10
    arrange(-freq) %>%
    head(n = 10) %>%
    
    rename(com_area = dropoff_community_area) %>%
    mutate(category = "Dropoff")
  ) %>% 
  
  # Bar plot
  plot_ly(x      =~ com_area, 
          y      =~ freq, 
          type   = "bar",
          color  =~ category,
          colors = c("#FAA916","#02040F")) %>%
  layout(xaxis   = list(title = "Community Area",
                        type  = "category"),
         yaxis   = list(title = "Number of taxi trips"),
         legend  = list(x = 0.4, y = 0.95, orientation = 'h'))
  
```

### Map pickup
```{r}
# By changing pickup for dropoff we ended up with the same map
taxi %>%
  
  # Latitude and longitude of centroid, not exact location of pickup
  # Collapse by latitude and longitude
  filter(!is.na(pickup_centroid_latitude)) %>%
  group_by(pickup_centroid_latitude, pickup_centroid_longitude) %>%
  summarise(freq = n()) %>% 
  
  mutate(category = "pickup") %>%
  rename(lat = pickup_centroid_latitude, 
         lon = pickup_centroid_longitude) %>%
  
  # Map
  leaflet() %>%
  setView(lng  = -87.629799, 
          lat  =  41.878113, 
          zoom = 12) %>%
  addTiles() %>%
  addCircleMarkers(lng         =~ lon,
                   lat         =~ lat, 
                   radius      =~ freq/10000, 
                   color       = I("#BA1B1D"), 
                   stroke      = T, 
                   fillOpacity = 0.8)
```

## Other providers
### Summary of NAs
```{r, warning = F, message = F}
other %>%
  is.na() %>%
  colSums() %>%
  data.frame(countNA = .) %>%
  add_rownames(var = "Variable") %>%
  filter(countNA > 0) %>%
  kable(col.names = c("","Number of NAs")) %>%
  kable_styling(full_width = F)
```

## Crime
### General summary 
```{r, warning = F, message = F}
crime %>%
  select(-x.coordinate,
         -y.coordinate, 
         -latitude, 
         -longitude) %>%
  select_if(is.numeric) %>% 
  as.data.frame() %>%
  papeR::summarize(show.NAs = T) %>%
  kable() %>%
  kable_styling(full_width = F)
```

### Summary of NAs
```{r, warning = F, message = F}
crime %>%
  is.na() %>%
  colSums() %>%
  data.frame(countNA = .) %>%
  add_rownames(var = "Variable") %>%
  filter(countNA > 0) %>%
  kable(col.names = c("","Number of NAs")) %>%
  kable_styling(full_width = F)
```




















